apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: agentland
spec:
  selector:
    app.kubernetes.io/name: gateway
  ports:
  - name: http
    port: 8080
    targetPort: http
