---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentland.fl0rencess720.app
  resources:
  - agentruntimes
  - agentsessions
  - codeinterpreters
  - sandboxclaims
  - sandboxes
  - sandboxpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentland.fl0rencess720.app
  resources:
  - agentruntimes/finalizers
  - agentsessions/finalizers
  - codeinterpreters/finalizers
  verbs:
  - update
- apiGroups:
  - agentland.fl0rencess720.app
  resources:
  - agentruntimes/status
  - agentsessions/status
  - codeinterpreters/status
  - sandboxclaims/status
  - sandboxes/status
  - sandboxpools/status
  verbs:
  - get
  - patch
  - update
