{{- if .Values.gateway.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentland.componentName" (dict "root" . "name" .Values.gateway.deployment.name) }}
  namespace: {{ .Values.namespaces.system }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: agentland
spec:
  replicas: {{ .Values.gateway.deployment.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/part-of: agentland
    spec:
      serviceAccountName: {{ include "agentland.componentName" (dict "root" . "name" .Values.gateway.serviceAccount.name) }}
      containers:
        - name: gateway
          image: "{{ .Values.gateway.deployment.image.repository }}:{{ .Values.gateway.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.deployment.image.pullPolicy }}
          args:
{{ toYaml .Values.gateway.deployment.args | indent 12 }}
          env:
            - name: AL_REDIS_ADDR
              value: {{ default (printf "%s:%v" (include "agentland.componentName" (dict "root" . "name" .Values.redis.service.name)) .Values.redis.service.port) .Values.gateway.deployment.env.AL_REDIS_ADDR | quote }}
            - name: AL_REDIS_PASSWORD
              value: {{ .Values.gateway.deployment.env.AL_REDIS_PASSWORD | quote }}
            - name: AL_REDIS_DB
              value: {{ .Values.gateway.deployment.env.AL_REDIS_DB | quote }}
            - name: AL_AGENTCORE_ADDRESS
              value: {{ default (printf "%s:%v" (include "agentland.componentName" (dict "root" . "name" .Values.agentcore.agentcoreService.name)) .Values.agentcore.agentcoreService.port) .Values.gateway.deployment.env.AL_AGENTCORE_ADDRESS | quote }}
            - name: AL_GATEWAY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AL_SANDBOX_JWT_ISSUER
              value: {{ default (include "agentland.componentName" (dict "root" . "name" .Values.gateway.service.name)) .Values.gateway.deployment.env.AL_SANDBOX_JWT_ISSUER | quote }}
            - name: AL_SANDBOX_JWT_AUDIENCE
              value: {{ .Values.gateway.deployment.env.AL_SANDBOX_JWT_AUDIENCE | quote }}
            - name: AL_SANDBOX_JWT_TTL
              value: {{ .Values.gateway.deployment.env.AL_SANDBOX_JWT_TTL | quote }}
            - name: AL_SANDBOX_JWT_KID
              value: {{ .Values.gateway.deployment.env.AL_SANDBOX_JWT_KID | quote }}
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}
