apiVersion: agentland.fl0rencess720.app/v1alpha1
kind: CodeRunner
metadata:
  labels:
    app.kubernetes.io/name: agentland
    app.kubernetes.io/managed-by: kustomize
  name: coderunner-sample
spec:
  # TODO(user): Add fields here
